workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: appstore_credentials
    environment:
      node: 20
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: GSW.com.gyomukaizennavi
      vars:
        APP_ID: GSW.com.gyomukaizennavi
        AD_ENV: prod
    triggering:
      events:
        - tag
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Capacitor sync
        script: npx cap sync ios
      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($BUILD_NUMBER))
      - name: Build ipa
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        submit_to_testflight: true
